services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "10000:10000"
    volumes:
      - ./app:/app/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
