from typing import List
from pydantic import BaseModel, Field

class UniquenessPayload(BaseModel):
    """
    Defines the structure of the JSON payload expected by the
    /validate-global-uniqueness endpoint.
    """
    fingerprints: List[str] = Field(
        ...,
        description="A list of 64-bit SimHash fingerprints generated by a Tier 1 proof.",
        min_length=1,
        examples=[["7379400833890108899", "1098359420495924393", "843904281978419841"]]
    )

class UniquenessResponse(BaseModel):
    """
    Defines the structure of the JSON response sent back by the endpoint.
    """
    total_fingerprints_received: int
    new_fingerprints_found: int
    duplicate_fingerprints_found: int
    global_uniqueness_score: float = Field(
        ...,
        description="A score from 0.0 to 1.0 indicating the proportion of new fingerprints."
    )
